### ISSUE TITLE
Navigation Component for Desktop view

### ISSUE THREAD

**Issue by noegeler** [d-lama/d-lama-webapp#20]
**Link to User Story**
[1018](https://github.com/d-lama/.github/blob/main/mgmt/product_backlog.md#1018)

**Feature Description**
Create a navigation Bar for desktop view (Admin) that can navigate to options and logout.

- [x] Add Navigation bar component for deskop on top of screen if the user is admin
- [x] Add hidden Navigation component that slides in from the left when clicked on top left hamburger button. 
- [ ] Add link to options within the navigation
- [ ] Add link to home screen within the navigation
- [x] Add logout button in the navigation on the top right that logs admin out
- [ ] Add navigation component for all screens concerning admin. Home screen, Options Screen, Create Project Screen, Project Overview Screen

**Additional context**

- Component for Mobile view looks different and fulfills a different purpose.
- Additional navigation items for navigation component may come in the future

**Comment by schazadm** [comment]
Navigation is done, but not every view is ready to direct to
